import type { SamplerParams } from "./types";

const shared = {
  repeat: 0.04,
  reverse: 0.1,
  bedJump: 0.12,
  crossfade: 0.004,
  bedCrossfade: 0.04,
} as const;

export const PRESETS: Record<string, SamplerParams> = {
  dorees: {
    ...shared,
    id: "dorees",
    name: "Dorées",
    shredRate: 4,
    shredMin: 0.014,
    shredMax: 0.09,
    shredGain: 0.42,
    shredWidth: 0.45,
    bedMin: 0.7,
    bedMax: 1.8,
    bedGain: 0.95,
    bedWidth: 0.2,
    clickRate: 1.2,
    clickGain: 0.22,
    lowpass: 7800,
    limiter: true,
    limitThreshold: 0.78,
    outputGain: 0.92,
    contour: "swell",
  },
  doki: {
    ...shared,
    id: "doki",
    name: "Doki",
    shredRate: 20,
    shredMin: 0.008,
    shredMax: 0.04,
    repeat: 0.05,
    reverse: 0.14,
    shredGain: 0.9,
    shredWidth: 0.9,
    bedMin: 0.35,
    bedMax: 1.1,
    bedGain: 0.5,
    bedWidth: 0.4,
    bedJump: 0.35,
    clickRate: 2.2,
    clickGain: 0.16,
    lowpass: 9000,
    limiter: true,
    limitThreshold: 0.7,
    outputGain: 0.88,
    contour: "dropout",
    crossfade: 0.002,
    bedCrossfade: 0.02,
  },
  perdre: {
    ...shared,
    id: "perdre",
    name: "Perdre",
    shredRate: 15,
    shredMin: 0.006,
    shredMax: 0.05,
    shredGain: 0.72,
    shredWidth: 1,
    bedMin: 0.45,
    bedMax: 1.3,
    bedGain: 0.78,
    bedWidth: 0.75,
    bedJump: 0.22,
    clickRate: 7,
    clickGain: 0.34,
    lowpass: 8600,
    limiter: true,
    limitThreshold: 0.52,
    outputGain: 0.84,
    contour: "fade",
    crossfade: 0.0016,
    bedCrossfade: 0.02,
  },
  lexo: {
    ...shared,
    id: "lexo",
    name: "Lexo",
    shredRate: 8,
    shredMin: 0.02,
    shredMax: 0.18,
    repeat: 0.06,
    reverse: 0.08,
    shredGain: 0.62,
    shredWidth: 0.5,
    bedMin: 0.5,
    bedMax: 1.5,
    bedGain: 0.9,
    bedWidth: 0.28,
    bedJump: 0.18,
    clickRate: 2.4,
    clickGain: 0.2,
    lowpass: 4200,
    limiter: true,
    limitThreshold: 0.6,
    outputGain: 0.96,
    contour: "flat",
    crossfade: 0.006,
    bedCrossfade: 0.035,
  },
  muraille: {
    ...shared,
    id: "muraille",
    name: "Muraille",
    shredRate: 0,
    shredMin: 0.02,
    shredMax: 0.08,
    repeat: 0,
    reverse: 0,
    shredGain: 0,
    shredWidth: 0,
    bedMin: 2.4,
    bedMax: 5.5,
    bedGain: 1,
    bedWidth: 0,
    bedJump: 0.04,
    clickRate: 0,
    clickGain: 0,
    lowpass: 14000,
    limiter: false,
    limitThreshold: 0.9,
    outputGain: 0.25,
    contour: "still",
    crossfade: 0.01,
    bedCrossfade: 0.08,
  },
};

export const PRESET_ORDER = ["dorees", "doki", "perdre", "lexo", "muraille"] as const;

export type PresetId = (typeof PRESET_ORDER)[number];

export function cloneParams(params: SamplerParams): SamplerParams {
  return { ...params };
}
